version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_DATABASE=root"
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 33064:3306
    volumes:
      - dbdata:/var/lib/mysql:cached
  db_test:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_DATABASE=root"
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 33065:3306
    volumes:
      - dbdata_test:/var/lib/mysql:cached
volumes:
  dbdata:
  dbdata_test:
